packages:
  - .

strictPeerDependencies: true
noFrozenLockfile: true

onlyBuiltDependencies:
  - esbuild

overrides:
  eslint: ">=10.0.0"
  '@eslint/js': ">=10.0.0"
  '@stylistic/eslint-plugin': '>=5.0.0'
