packages:
  - .

strictPeerDependencies: true
noFrozenLockfile: true

onlyBuiltDependencies:
  - esbuild

overrides:
  eslint: "^9"
  '@eslint/js': "^9"
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@types/node': '^24'
