packages:
  - .

noFrozenLockfile: true

onlyBuiltDependencies:
  - esbuild

overrides:
  '@eslint/js': ^9
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@types/node': ^24
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  eslint: ^9

strictPeerDependencies: true
